package com.example.MyBookShopApp.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@Entity
@Table(name = "authors")
@ApiModel(description = "data model of author entity")
@NoArgsConstructor
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value ="author id generated by db", position = 1)
    private Integer id;
    @ApiModelProperty(value = "first name of author", example = "John", position = 2)
    private String firstName;
    @ApiModelProperty(value = "last name of author", example = "Wick", position = 3)
    private String lastName;
    @Column(columnDefinition = "TEXT")
    private String authorHistory;

    @JsonIgnore
    @OneToMany(mappedBy = "author")
    List<Book> bookList = new ArrayList<>();

    @Override
    public String toString() {
        return firstName + " " + lastName;
    }
}