insert into authors (id, first_name, last_name) values (1, 'Maurizio', 'Pardi');
insert into authors (id, first_name, last_name) values (2, 'Court', 'Trenholme');
insert into authors (id, first_name, last_name) values (3, 'Tye', 'Burgess');
insert into authors (id, first_name, last_name) values (4, 'Frederica', 'Nana');
insert into authors (id, first_name, last_name) values (5, 'Madelaine', 'Verman');
insert into authors (id, first_name, last_name) values (6, 'Jakob', 'Parrin');
insert into authors (id, first_name, last_name) values (7, 'Maryrose', 'McAlister');
insert into authors (id, first_name, last_name) values (8, 'Meade', 'Rigeby');
insert into authors (id, first_name, last_name) values (9, 'Rustin', 'Westmancoat');
insert into authors (id, first_name, last_name) values (10, 'Cull', 'Redhole');
insert into authors (id, first_name, last_name) values (11, 'Eberhard', 'Myrtle');
insert into authors (id, first_name, last_name) values (12, 'Veronique', 'Farrow');
insert into authors (id, first_name, last_name) values (13, 'Ilario', 'Hanster');
insert into authors (id, first_name, last_name) values (14, 'Ambros', 'Hackney');
insert into authors (id, first_name, last_name) values (15, 'Cherice', 'Grent');
insert into authors (id, first_name, last_name) values (16, 'Nevins', 'Kluss');
insert into authors (id, first_name, last_name) values (17, 'Gerri', 'Brumfitt');
insert into authors (id, first_name, last_name) values (18, 'Lil', 'Sacase');
insert into authors (id, first_name, last_name) values (19, 'Sean', 'Aldins');
insert into authors (id, first_name, last_name) values (20, 'Prentice', 'Edie');
insert into authors (id, first_name, last_name) values (21, 'Spense', 'Redmell');
insert into authors (id, first_name, last_name) values (22, 'Ty', 'Loffel');
insert into authors (id, first_name, last_name) values (23, 'Elvera', 'Drysdell');
insert into authors (id, first_name, last_name) values (24, 'Yance', 'Klimentov');
insert into authors (id, first_name, last_name) values (25, 'Dieter', 'Annandale');
insert into authors (id, first_name, last_name) values (26, 'Ewan', 'Swinden');
insert into authors (id, first_name, last_name) values (27, 'Lazar', 'Burkin');
insert into authors (id, first_name, last_name) values (28, 'Eamon', 'Beedell');
insert into authors (id, first_name, last_name) values (29, 'Mufi', 'Maris');
insert into authors (id, first_name, last_name) values (30, 'Caldwell', 'Legging');
insert into authors (id, first_name, last_name) values (31, 'Hedwiga', 'Adams');
insert into authors (id, first_name, last_name) values (32, 'Isabella', 'Arnecke');
insert into authors (id, first_name, last_name) values (33, 'Web', 'Benoist');
insert into authors (id, first_name, last_name) values (34, 'Nalani', 'Danilyuk');
insert into authors (id, first_name, last_name) values (35, 'Binnie', 'Gerrad');
insert into authors (id, first_name, last_name) values (36, 'Gunilla', 'Fursland');
insert into authors (id, first_name, last_name) values (37, 'Standford', 'Brewood');
insert into authors (id, first_name, last_name) values (38, 'Niels', 'Suermeiers');
insert into authors (id, first_name, last_name) values (39, 'Marsha', 'Acom');
insert into authors (id, first_name, last_name) values (40, 'Randell', 'Coie');
insert into authors (id, first_name, last_name) values (41, 'Eldredge', 'Torrejon');
insert into authors (id, first_name, last_name) values (42, 'Demetre', 'DelaField');
insert into authors (id, first_name, last_name) values (43, 'Meryl', 'Lack');
insert into authors (id, first_name, last_name) values (44, 'Archibald', 'Forde');
insert into authors (id, first_name, last_name) values (45, 'Merill', 'Perkins');
insert into authors (id, first_name, last_name) values (46, 'Chas', 'Spickett');
insert into authors (id, first_name, last_name) values (47, 'Randolph', 'Southcott');
insert into authors (id, first_name, last_name) values (48, 'Livvie', 'Beernaert');
insert into authors (id, first_name, last_name) values (49, 'Maryjo', 'MacKniely');
insert into authors (id, first_name, last_name) values (50, 'Nara', 'Nuemann');
insert into authors (id, first_name, last_name) values (51, 'Rani', 'Steanson');
insert into authors (id, first_name, last_name) values (52, 'Marion', 'Dmtrovic');
insert into authors (id, first_name, last_name) values (53, 'Milo', 'McNevin');
insert into authors (id, first_name, last_name) values (54, 'Shane', 'Bonhan');
insert into authors (id, first_name, last_name) values (55, 'Jedediah', 'Huckerbe');


insert into books (id, price, price_old, title, author_id) values (1, 2386, 3737, 'Alphazap', 1);
insert into books (id, price, price_old, title, author_id) values (2, 1794, 2517, 'Viva', 2);
insert into books (id, price, price_old, title, author_id) values (3, 2251, 2855, 'Lotstring', 3);
insert into books (id, price, price_old, title, author_id) values (4, 2144, 3109, 'Bigtax', 4);
insert into books (id, price, price_old, title, author_id) values (5, 2744, 2257, 'Sonsing', 5);
insert into books (id, price, price_old, title, author_id) values (6, 1286, 2803, 'Aerified', 6);
insert into books (id, price, price_old, title, author_id) values (7, 2096, 3399, 'Flexidy', 7);
insert into books (id, price, price_old, title, author_id) values (8, 988, 3200, 'Rank', 8);
insert into books (id, price, price_old, title, author_id) values (9, 870, 2909, 'Subin', 9);
insert into books (id, price, price_old, title, author_id) values (10, 1658, 3291, 'Subin', 10);
insert into books (id, price, price_old, title, author_id) values (11, 1264, 3013, 'Transcof', 11);
insert into books (id, price, price_old, title, author_id) values (12, 1519, 3771, 'Greenlam', 12);
insert into books (id, price, price_old, title, author_id) values (13, 1724, 3563, 'Trippledex', 13);
insert into books (id, price, price_old, title, author_id) values (14, 2239, 2382, 'Gembucket', 14);
insert into books (id, price, price_old, title, author_id) values (15, 673, 1449, 'Fixflex', 15);
insert into books (id, price, price_old, title, author_id) values (16, 2662, 2846, 'Namfix', 16);
insert into books (id, price, price_old, title, author_id) values (17, 2913, 2803, 'Gembucket', 17);
insert into books (id, price, price_old, title, author_id) values (18, 1974, 2403, 'Bitwolf', 18);
insert into books (id, price, price_old, title, author_id) values (19, 1883, 2214, 'Cardify', 19);
insert into books (id, price, price_old, title, author_id) values (20, 1969, 2183, 'Alphazap', 20);
insert into books (id, price, price_old, title, author_id) values (21, 2774, 2863, 'Wrapsafe', 21);
insert into books (id, price, price_old, title, author_id) values (22, 1099, 2181, 'Holdlamis', 22);
insert into books (id, price, price_old, title, author_id) values (23, 1317, 1100, 'Pannier', 23);
insert into books (id, price, price_old, title, author_id) values (24, 603, 3739, 'Bitwolf', 24);
insert into books (id, price, price_old, title, author_id) values (25, 832, 3288, 'Flexidy', 25);
insert into books (id, price, price_old, title, author_id) values (26, 1211, 1766, 'Konklux', 26);
insert into books (id, price, price_old, title, author_id) values (27, 1606, 2476, 'Rank', 27);
insert into books (id, price, price_old, title, author_id) values (28, 1650, 3044, 'Zathin', 28);
insert into books (id, price, price_old, title, author_id) values (29, 2799, 3952, 'Konklux', 29);
insert into books (id, price, price_old, title, author_id) values (30, 2987, 2947, 'Sonair', 30);
insert into books (id, price, price_old, title, author_id) values (31, 564, 3624, 'Bytecard', 31);
insert into books (id, price, price_old, title, author_id) values (32, 1153, 2906, 'Gembucket', 32);
insert into books (id, price, price_old, title, author_id) values (33, 532, 1446, 'Tin', 33);
insert into books (id, price, price_old, title, author_id) values (34, 522, 1135, 'Sonair', 34);
insert into books (id, price, price_old, title, author_id) values (35, 855, 2118, 'Greenlam', 35);
insert into books (id, price, price_old, title, author_id) values (36, 2497, 2028, 'Overhold', 36);
insert into books (id, price, price_old, title, author_id) values (37, 2624, 2932, 'Bitchip', 37);
insert into books (id, price, price_old, title, author_id) values (38, 1543, 1401, 'Y-Solowarm', 38);
insert into books (id, price, price_old, title, author_id) values (39, 901, 3286, 'Konklux', 39);
insert into books (id, price, price_old, title, author_id) values (40, 2067, 2877, 'Overhold', 40);
insert into books (id, price, price_old, title, author_id) values (41, 601, 3197, 'Kanlam', 41);
insert into books (id, price, price_old, title, author_id) values (42, 757, 3947, 'Sub-Ex', 42);
insert into books (id, price, price_old, title, author_id) values (43, 1574, 1834, 'Holdlamis', 43);
insert into books (id, price, price_old, title, author_id) values (44, 927, 2273, 'Mat Lam Tam', 44);
insert into books (id, price, price_old, title, author_id) values (45, 1624, 3186, 'Tin', 45);
insert into books (id, price, price_old, title, author_id) values (46, 2881, 1079, 'Rank', 46);
insert into books (id, price, price_old, title, author_id) values (47, 2608, 2672, 'Solarbreeze', 47);
insert into books (id, price, price_old, title, author_id) values (48, 1769, 1487, 'Stim', 48);
insert into books (id, price, price_old, title, author_id) values (49, 1463, 3439, 'Aerified', 49);
insert into books (id, price, price_old, title, author_id) values (50, 1997, 3309, 'Veribet', 50);
insert into books (id, price, price_old, title, author_id) values (51, 1839, 3522, 'Pannier', 51);
insert into books (id, price, price_old, title, author_id) values (52, 651, 1863, 'Stringtough', 52);
insert into books (id, price, price_old, title, author_id) values (53, 1326, 3127, 'Namfix', 53);
insert into books (id, price, price_old, title, author_id) values (54, 2009, 1264, 'Aerified', 54);
insert into books (id, price, price_old, title, author_id) values (55, 2298, 3378, 'Toughjoyfax', 55);
